
#ifndef __NDNROUTINGCONSTANT_H_
#define __NDNROUTINGCONSTANT_H_
#define NDNROUTING_MTU 1500
#define NDNROUTING_HELLOINTERVAL 10
#define NDNROUTING_DDRETRANSMISSION_INTERVAL 5
#define NDNROUTING_ROUTERDEADINTERVAL 40

#endif